language: java

install:
  # markdown-link-check
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

script: 
  - jdk_switcher use oraclejdk8
  - ./download_processing.sh
  - ./download_minim.sh
  - ./build.sh
  # Check dead links
<<<<<<< HEAD
  #- find . -name \*.md -exec markdown-link-check {} \; 2>/dev/null | egrep "[✖]"
=======
  # - find . -name \*.md -exec markdown-link-check {} \; 2>/dev/null | egrep "[✖]"
>>>>>>> develop

after_failure:
  - find . | egrep "processing-java"

after_success:
  - find . | egrep "processing-java"
